export const Tablica = [
  'aborcja',
  'adopcja',
  'alkoholizm',
  'amoris laetitia',
  'antykoncepcja',
  'ars amandi',
  'bezpłodność',
  'bicie dzieci',
  'biochemia',
  'bliskość',
  'ból',
  'bud',
  'budowanie więzi',
  'chodzenie ze sobą',
  'chora miłość',
  'choroba',
  'choroby',
  'choroby układu płciowego',
  'ciąża',
  'ciche dni',
  'cielesność',
  'córeczka tatusia',
  'cykl płodności',
  'czas we we dwoje',
  'czułość',
  'czystość',
  'dbanie o siebie',
  'dda',
  'depresja',
  'depresja poporodowa',
  'dialog',
  'dom',
  'domowy kościół',
  'dotyk',
  'dps',
  'dystans',
  'dziadkowie',
  'dzieci',
  'dzieci bez chrztu',
  'dziecko',
  'dziecko przed ślubem',
  'edukacja seksualna',
  'ekologia',
  'endometrioza',
  'eros',
  'erotyka',
  'feminizm',
  'finanse',
  'gender',
  'genetyka',
  'ghosting',
  'granice',
  'grzechy seksualne',
  'historia',
  'homoseksualizm',
  'hormony',
  'hospicjum perinatalne',
  'idee',
  'in vitro',
  'intuicja',
  'intymność',
  'język ciała',
  'języki miłości',
  'kabaret',
  'karmienie piersią',
  'kłótnia',
  'kobieta',
  'kochać siebie',
  'komentarze biblijne',
  'komunikacja',
  'konflikt',
  'kryteria do małżeństwa',
  'krytyka',
  'kryzys',
  'kultura',
  'lęk',
  'macierzyństwo',
  'małe przyjemności',
  'małżeństwa mieszane',
  'małżeństwo',
  'masturbacja',
  'mąż',
  'media',
  'mediacja',
  'menopauza',
  'mentalizacja',
  'metody naturalne',
  'męska płodność',
  'męskość i kobiecość',
  'mężczyzna',
  'miesiączka',
  'mikrochimeryzm',
  'miłość',
  'miłość 60 plus',
  'miłość siebie',
  'molestowanie seksualne',
  'moralność',
  'mózg',
  'nagość',
  'nałóg',
  'namiętność',
  'naprotechnologia',
  'narzeczeństwo',
  'nastolatek',
  'nauczanie kościoła',
  'niebo',
  'nienarodzone',
  'niepełnosprawność',
  'niepłodność',
  'niesakramentalni',
  'nieważne małżeństwo',
  'nowe technologie',
  'noworodek',
  'nowotwór',
  'objawienie',
  'obserwacja płodności',
  'ocaleńcy',
  'odkochanie',
  'odpoczynek',
  'odrzucenie',
  'ojcostwo',
  'oralne',
  'oświadczyny',
  'owulacja',
  'papież',
  'płciowość',
  'płodność',
  'po porodzie',
  'pochwica',
  'początek życia',
  'poczęcie',
  'poczucie winy',
  'podróż poślubna',
  'pojednanie',
  'polecane filmy',
  'połóg',
  'pornografia',
  'poronienie',
  'poród',
  'powołanie',
  'poza chrześcijaństwem',
  'prawa rodziców',
  'premenopauza',
  'prezenty',
  'prokreacja',
  'prolife',
  'prostata',
  'przekaz wiary dzieciom',
  'przemoc',
  'przerwa w związku',
  'przygotowanie do związku',
  'przyjaźń',
  'przyjemność',
  'przytulanie',
  'quiz',
  'randka',
  'relacja',
  'relacje',
  'rodzeństwo',
  'rodzic',
  'rodzic chrzestny',
  'rodzicielstwo',
  'rodzina pochodzenia',
  'romans',
  'rozmowa',
  'rozpoznawanie płodności',
  'rozrywka',
  'rozstanie',
  'rozwód',
  'rozwój dziecka',
  'różnice',
  'rytuał',
  'sakrament małżeństwa',
  'samotność',
  'seks młodzieży',
  'seks przed ślubem',
  'seks w ciąży',
  'seksoholizm',
  'seksualność',
  'seksualność dziecka',
  'separacja',
  'singiel',
  'skutki aborcji',
  'słowo boże',
  'społeczne',
  'staranie się o dziecko',
  'sterylizacja',
  'strata',
  'strata dziecka',
  'stworzenie człowieka',
  'style przywiązania',
  'sumienie',
  'szczerość',
  'ślub',
  'śmierć',
  'tabletka poronna',
  'terapia',
  'teściowie',
  'toksyczny związek',
  'uczucia',
  'wady letalne',
  'walka płci',
  'wcielenie',
  'wesele',
  'wierność',
  'wkładka domaciczna',
  'wsparcie',
  'współżycie seksualne',
  'wstrzemięźliwość',
  'wybaczenie',
  'wybory',
  'wychowanie dzieci',
  'zaangażowanie',
  'zabawa',
  'zaburzenia seksualności',
  'zagrożenia w sieci',
  'zakochanie',
  'zaręczyny',
  'zazdrość',
  'zdrada',
  'zespół downa',
  'złamane serce',
  'złość',
  'zwyczaje',
  'żałoba'
]
